VANTAGE Software: Model Class Reference
Model Class Reference
Model is a class used to store the estimation methods that utilize both TOF and camera data.
Public Member Functions
Model (manifestFilename, configDirecName, dataprocessing)
Class Constructor:
function ComputeStateOutput ()
A method for looping through optical data and performing sensor fusion to return a final state output Get directory of optical frames.
function this = CombineResults (pos, t)
Combine results from ComputeStateOutput and TOF processing.
function predPos = PredictPositionFromTOF (CubeSat, time)
function pos = RunSensorFusion (isSystemCentroid, camOrigin, camVecs, pos_TOF)
A method for approximating a cubesat centroid using a weighted centroiding method.
function pos = SensorFusion (camOrigin, camVec, pos_TOF)
A method for approximating a cubesat centroid using a weighted centroiding method.
function PredictionModel ()
I don't know what exactly this method is supposed to do.
function OutputStateVector ()
A method for outputting the state vectors for all identified cubesats.
function p = ransacLine (x, y, maxDistance)
% ransac line fitting for obfuscation
Public Attributes
Deployer Deployer
Deployer class.
Truth_VCF
Truth data.
Transform Transform
Transform class.
TimeMan TimeMan
Time Manager Class.
Optical Optical
Optical camera class.
TOF TOF
TOF camera class.
Private Member Functions
function Truth = processTruthData (truthFilename)
Read json truth file.
Detailed Description
Model is a class used to store the estimation methods that utilize both TOF and camera data.
Definition at line 19 of file Model.m.
Constructor & Destructor Documentation
Model (manifestFilename, configDirecName, dataprocessing)
Class Constructor:
Parameters
manifestFilename full filename of manifest JSON file
configDirecName The configuration directory name
Returns
A reference to an initialized Model object
Definition at line 95 of file Model.m.
References Model.Deployer, Model.Optical, Model.processTruthData(), Model.TOF, and Model.Transform.
Member Function Documentation
function this = CombineResults (pos, t)
Combine results from ComputeStateOutput and TOF processing.
Returns
this Updated object with centroids_VCF and time parameters
Author
Dylan Bossie
Date
11-Apr-2019
Definition at line 266 of file Model.m.
References CubeSat.centroids_VCF, Deployer.CubesatArray, and CubeSat.time.
Referenced by Model.ComputeStateOutput().
function ComputeStateOutput ()
A method for looping through optical data and performing sensor fusion to return a final state output Get directory of optical frames.
Parameters
this The object
Definition at line 140 of file Model.m.
References CubeSat.centroids_VCF, Model.CombineResults(), Deployer.CubesatArray, Optical.CubeSats, Optical.CurrentFrameCount, Optical.DataDirec, CubeSat.evalTofFit(), Optical.FindBackground(), Optical.findLastImagePixel(), Optical.Frame, Deployer.GetCamOriginVCF(), Deployer.GetNumCubesats(), Deployer.numCubesats, Model.Optical, Optical.OpticalProcessing(), Optical.rangeStart, Optical.readInputFramesFromImages(), Model.RunSensorFusion(), Deployer.testScenario, CubeSat.time, and Optical.Timestamps.
Referenced by Test_Optical.test100mData().
function OutputStateVector ()
A method for outputting the state vectors for all identified cubesats.
Parameters
sampleparameter sampledescription
Returns
samplereturn
Definition at line 490 of file Model.m.
function PredictionModel ()
I don't know what exactly this method is supposed to do.
Parameters
this The object
Returns
{ description_of_the_return_value }
Definition at line 476 of file Model.m.
function predPos = PredictPositionFromTOF (CubeSat, time)
Definition at line 343 of file Model.m.
function Truth = processTruthData (truthFilename) private
Read json truth file.
Processes truth data
Parameters
truthFilename full filename of truth data JSON file
Returns
struct containing truth data for the current execution of VANTAGE post processing
Author
Joshua Kirby
Date
03-Mar-2019
Generated fields of Truth:
Definition at line 541 of file Model.m.
References Deployer.testScenario.
Referenced by Model.Model().
function p = ransacLine (x, y, maxDistance)
% ransac line fitting for obfuscation
This function uses the ransac algorithm to fit a line to noisy data
Parameters
x x coordinates to fit
y y coordinates to fit
maxDistance The maximum distance from the line
Returns
polyfit line
Author
Justin Fay
Date
21-Feb-2019
Definition at line 503 of file Model.m.
function pos = RunSensorFusion (isSystemCentroid, camOrigin, camVecs, pos_TOF)
A method for approximating a cubesat centroid using a weighted centroiding method.
Parameters
this The object
isSystemCentroid Indicates if system centroid
camOrigin camera origin in the VANTAGE Cartesian Frame
camVecs cell array of vectors pointing from camera origin to estimated centroid in VCF
pos_TOF VCF position estimates from the TOF sensor suite
Returns
pos position estimate of cubesat centroids in the VCF frame using both sensor method returns
Definition at line 351 of file Model.m.
References Deployer.GetNumCubesats(), and Model.SensorFusion().
Referenced by Model.ComputeStateOutput().
function pos = SensorFusion (camOrigin, camVec, pos_TOF)
A method for approximating a cubesat centroid using a weighted centroiding method.
Parameters
this The object
camOrigin camera origin in the VANTAGE Cartesian Frame
camVec vector pointing from camera origin to estimated centroid in VCF
pos_TOF VCF position estimate from the TOF sensor suite
Returns
pos position estimate of cubesat centroid in the VCF frame using both sensor method returns
Definition at line 410 of file Model.m.
References Optical.OpticalWeighting(), and TOF.TofWeighting().
Referenced by Model.RunSensorFusion().
Member Data Documentation
Deployer
Deployer class.
Definition at line 30 of file Model.m.
Referenced by TOF.associateCentroids(), Validate.ComputeMeanVelocity(), Validate.generateErrorPlot(), Optical.ImageProcessing(), TOF.loadPcFile(), Model.Model(), Optical.occlusionCut(), Test_Fusion.testFullSystem(), Test_TOF.testTOFProcessing(), TOF.TOFProcessing(), Validate.Validate(), and VANTAGE_main().
Optical
Optical camera class.
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 71 of file Model.m.
Referenced by Model.ComputeStateOutput(), Model.Model(), Test_Optical.testPipeline(), TOF.TofWeighting(), and VANTAGE_Wrapper().
TimeMan
Time Manager Class.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 58 of file Model.m.
Referenced by TOF.TOFProcessing().
TOF
TOF camera class.
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 82 of file Model.m.
Referenced by Model.Model().
Transform
Transform class.
Note
This property has non-standard access specifiers: SetAccess = Protected, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 47 of file Model.m.
Referenced by TOF.associateCentroids(), Model.Model(), and TOF.plotResults().
Truth_VCF
Truth data.
Definition at line 38 of file Model.m.
Referenced by TOF.plotResults(), and TOF.TOFProcessing().
The documentation for this class was generated from the following file:
+VANTAGE/+PostProcessing/Model.m