VANTAGE Software: TimeManager Class Reference
TimeManager Class Reference
% Classdef A class used to convert between various time frames. A limitation is that all truth, tof, and optical times (date strings) are expected to be in the same time zone.
Public Member Functions
TimeManager (SensorData, testType, ModelRef)
Class Constructor Get DateVecZero.
function syncTruthData (ModelRef)
function dv = datevecFromTofFilename (TOF_filename, testType)
function dv = datevecFromOpticalFilename (Opt_filename, TestType)
function t = VantageTime (filenames, filetype, TestType)
function ds = VantageTime2DateStr (t)
Public Attributes
TofDateFormat = "yyyy_mm_dd_HH_MM_SS.FFF"
TruthDateFormat = "dd-mmm-yyyy HH:MM:SS.FFF"
Truth Date Format.
OpticalDateFormat = "yyyy_m_dd_HH_MM_SS_FFF"
Optical Date Format.
VantageDateFormat = "dd-mmm-yyyy HH:MM:SS.FFF"
Desired Output Date Format for VANTAGE.
DatevecZero
Datevec corresponding to t=0s.
Model ModelRef
Reference to the Model Class.
Detailed Description
% Classdef A class used to convert between various time frames. A limitation is that all truth, tof, and optical times (date strings) are expected to be in the same time zone.
% Properties
Definition at line 19 of file TimeManager.m.
Constructor & Destructor Documentation
TimeManager (SensorData, testType, ModelRef)
Class Constructor Get DateVecZero.
Constructs class using Transform.json config file
Returns
Class instance
Author
Joshua Kirby
Date
06-Apr-2019
Required fields of SensorData:
Definition at line 76 of file TimeManager.m.
References TimeManager.datevecFromTofFilename(), and TimeManager.ModelRef.
Member Function Documentation
function dv = datevecFromOpticalFilename (Opt_filename, TestType)
Definition at line 131 of file TimeManager.m.
Referenced by TimeManager.VantageTime().
function dv = datevecFromTofFilename (TOF_filename, testType)
Definition at line 120 of file TimeManager.m.
Referenced by TimeManager.TimeManager(), and TimeManager.VantageTime().
function syncTruthData (ModelRef)
Definition at line 103 of file TimeManager.m.
function t = VantageTime (filenames, filetype, TestType)
Definition at line 142 of file TimeManager.m.
References TimeManager.datevecFromOpticalFilename(), and TimeManager.datevecFromTofFilename().
function ds = VantageTime2DateStr (t)
Definition at line 194 of file TimeManager.m.
References TimeManager.DatevecZero.
Member Data Documentation
DatevecZero
Datevec corresponding to t=0s.
Definition at line 58 of file TimeManager.m.
Referenced by TimeManager.VantageTime2DateStr().
ModelRef
Reference to the Model Class.
Definition at line 65 of file TimeManager.m.
Referenced by TimeManager.TimeManager().
OpticalDateFormat = "yyyy_m_dd_HH_MM_SS_FFF"
Optical Date Format.
Default: "yyyy_m_dd_HH_MM_SS_FFF"
Definition at line 42 of file TimeManager.m.
TofDateFormat = "yyyy_mm_dd_HH_MM_SS.FFF"
Definition at line 32 of file TimeManager.m.
TruthDateFormat = "dd-mmm-yyyy HH:MM:SS.FFF"
Truth Date Format.
Default: "dd-mmm-yyyy HH:MM:SS.FFF"
Definition at line 34 of file TimeManager.m.
VantageDateFormat = "dd-mmm-yyyy HH:MM:SS.FFF"
Desired Output Date Format for VANTAGE.
Default: "dd-mmm-yyyy HH:MM:SS.FFF"
Definition at line 50 of file TimeManager.m.
The documentation for this class was generated from the following file:
+VANTAGE/+PostProcessing/TimeManager.m