VANTAGE Software: Validate Class Reference
Validate Class Reference
% Properties
Public Member Functions
Validate (configFilename, ModelRef, CorrelateTruthData)
% Class Constructor
function validateTOF ()
% Validate TOF %% Housekeeping and Allocation
function CubeSatFitted = fitCubeSatTraj (CubeSat, t, Type, t_fit, Model)
% Fit polynomial to CubeSat data
function [ Error , XError , YError , ZError ] = ProcessError (CubeSat, Truth)
% Plot error
function distance = ComputeTruthDistance (Model)
% Compute truth distance vector
function launch_time_diff = ComputeLaunchTime (CubeSat, Time, Truth)
% Compute time of cs launch
function [ pos_err , time_interp ] = InterpolateDistance (CSArray, timefitted, time, distance)
function meanvelocity = ComputeMeanVelocity (CubeSats, time, type)
% Compute mean velocity
function ErrorAnalysis (Model, SensorData, testDef)
% Compute mean error
function [ p1 , p2 ] = generateErrorPlot (d, mu, sigma, color)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% %% Author: Marshall Herr %% %% Purpose: To make nice plots of the error vs range of VANTAGE %% %% Inputs: %% - r: A vector of the range of each datapoint %% - mu: The mean error at each range given in r %% - sigma: The standard deviation of the error at each range given in %% r %% %% Outputs: %% - A cool plot %% %% Date Created: 22 March 2019 %% %% Last Editted: 22 March 2019 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function GenerateOutputFiles (matFileDirectory)
% Generate output report %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% Modular data output files
function [ updatedTruth , dt , n_vec , theta , offset_vec ] = PerformTruthDataCorrelation (MeasuredDataArray, TruthData, mostTrustedCubesat, should_debug)
% Correlate the truth data of a single, most trusted CubeSat {
function [ dt , n_vec , theta , offset_vec ] = CorrelationMachine (VANTAGE_Data, Truth_Data, should_debug)
% This does the grunt work for my Correlation fcns
function [ updatedTruth , dt , n_vec , theta , offset_vec ] = PerformTruthDataCorrelationMultiple (MeasuredDataArray, TruthData)
% Correlate the truth data using a weighted sum of all CubeSats {
function WriteUpdatedTruthData (updatedTruth, TruthFileName, dt, n_vec, theta, offset_vec)
% Write out new corrected truth data json text file and json corrections file gets the absolute path to the file
function masterPlotter (dataDirectory)
% Generates all of the plots {
function nicePlot (x, y, linespec, colors, plotLabels, plotTitle, legend_str, x_range)
% Makes nice plots
function structure = convolveMeasurements (structure, numElements)
% Convolves stuff
function outputStruct = extractMatFileData (fileStruct)
% Extracts all of the data from a folder of mat files
function f = errorPlot (x_req, x_S, x_M, x_100m, x_K, req, mu_err_S, mu_err_M, mu_err_100m, mu_err_K, sigma_err_S, sigma_err_M, sigma_err_100m, sigma_err_K, x_c, plotLabels, plotTitle, x_range)
% Generates all of the plots Plotting parameters
Public Attributes
CorrelateTruthData
Boolean for whether or not to auto update truth data.
ComputingResults
Model ModelRef
Model handle class.
Private Member Functions
function TOFpresentErrorsVsReqs (Model, SensorData)
TOF Processing.
Detailed Description
% Properties
Definition at line 19 of file Validate.m.
Constructor & Destructor Documentation
Validate (configFilename, ModelRef, CorrelateTruthData)
% Class Constructor
Constructs validate class
Parameters
Definition at line 48 of file Validate.m.
References Deployer.CubesatArray, Model.Deployer, Validate.ModelRef, Validate.PerformTruthDataCorrelationMultiple(), and Validate.WriteUpdatedTruthData().
Member Function Documentation
function launch_time_diff = ComputeLaunchTime (CubeSat, Time, Truth)
% Compute time of cs launch
Parameters
Definition at line 260 of file Validate.m.
Referenced by Validate.ErrorAnalysis().
function meanvelocity = ComputeMeanVelocity (CubeSats, time, type)
% Compute mean velocity
Compute mean velocity of all cubesats in current file
Parameters
Definition at line 336 of file Validate.m.
References Model.Deployer, and Deployer.testScenario.
Referenced by Validate.ErrorAnalysis().
function distance = ComputeTruthDistance (Model)
% Compute truth distance vector
Parameters
Definition at line 230 of file Validate.m.
Referenced by Validate.ErrorAnalysis().
function structure = convolveMeasurements (structure, numElements)
% Convolves stuff
This code shall produce error convolution fields
Parameters
structure The data structure from a specific test
numElements The number of elements within each field
Returns
structure The editted structure
Author
Marshall Herr
Date
16-Apr-2019
Required fields of structure:
Generated fields of structure:
Definition at line 1957 of file Validate.m.
Referenced by Validate.masterPlotter().
function [ dt , n_vec , theta , offset_vec ] = CorrelationMachine (VANTAGE_Data, Truth_Data, should_debug)
% This does the grunt work for my Correlation fcns
Determines the timeshift, rotation vector, rotation angle, and trnslation for truthdata wrt measurements
Parameters
VANTAGE_Data This is a struct that holds the measured times and positions for a single cubesat
Truth_Data This is a struct that holds the truth times and positions for the same cubesat
should_debug Boolian for if you want plot spam or not
Returns
dt The time shifting scalar applied to the truth data timestamps
n_vec The vector about which the truth data is rotated
theta The angle [rad] of the rotation around n_vec
offset_vec The translation applied to the truth data
Author
Marshall Herr
Date
15-Apr-2019
Required fields of VANTAGE_Data:
Required fields of Truth_Data:
Definition at line 1015 of file Validate.m.
Referenced by Validate.PerformTruthDataCorrelation(), and Validate.PerformTruthDataCorrelationMultiple().
function ErrorAnalysis (Model, SensorData, testDef)
% Compute mean error
Compute mean error for all tests and assimilate cubesat results
Parameters
Model Model class containing initial data
Returns
Author
Dylan Bossie
Date
14-Apr-2019
Required fields of Model:
Definition at line 406 of file Validate.m.
References Validate.ComputeLaunchTime(), Validate.ComputeMeanVelocity(), Validate.ComputeTruthDistance(), and Validate.InterpolateDistance().
function f = errorPlot (x_req, x_S, x_M, x_100m, x_K, req, mu_err_S, mu_err_M, mu_err_100m, mu_err_K, sigma_err_S, sigma_err_M, sigma_err_100m, sigma_err_K, x_c, plotLabels, plotTitle, x_range)
% Generates all of the plots Plotting parameters
This code shall produce an analysis plot
Parameters
x_req the independent variable of the plot vector associated to the req points
x_S the independent variable of the plot vector associated to the err_S points
x_M the independent variable of the plot vector associated to the err_M points
x_100m the independent variable of the plot vector associated to the err_100m points
x_K the independent variable of the plot vector associated to the err_K points
err_S the simulated test error vector
err_M the modular test error vector
err_100m the 100m test error vector
err_K the knitted test error vector
req an error requirements vector
x_c important independent variable values
plotLabels a cell containing {xlabel,ylabel}
plotTitle a string containing the plot title
x_range a 2 length vector containing [xmin,xmax]
Returns
f plot figure handle
Author
Marshall Herr
Date
16-Apr-2019
Generated fields of f:
Definition at line 2136 of file Validate.m.
Referenced by Validate.masterPlotter().
function outputStruct = extractMatFileData (fileStruct)
% Extracts all of the data from a folder of mat files
This code shall produce a structure with the data contained in the input folder
Parameters
fileStruct a struct which is generated by a dir() call and contains test data .mat files
outputStruct a structure with the following fields
distance = a cell array into which the ith mat files distance cell goes (cubesats are listed as farthest to nearest), velocity = a cell into which the ith mat files velocity goes, t_err = a vector into which the ith mat files t_err goes, v_err = a cell into which the ith mat files v_err goes, pos_err = a cell array into which the ith mat files pos_err cell goes (cubesats are listed as farthest to nearest)... this struct is sorted into outputStruct.velocity ascending order
Author
Marshall Herr
Date
16-Apr-2019
Generated fields of outputStruct:
Definition at line 2042 of file Validate.m.
Referenced by Validate.masterPlotter().
function CubeSatFitted = fitCubeSatTraj (CubeSat, t, Type, t_fit, Model)
% Fit polynomial to CubeSat data
Apply a linear fit to a CubeSat VCF XYZ input
Parameters
CubeSat Cell array or array of X Y Z values
t Timestamps
Returns
CubeSatFitted Array of XYZ values fitted
Author
Dylan Bossie
Date
11-Apr-2019
Required fields of Model:
Definition at line 148 of file Validate.m.
function [ p1 , p2 ] = generateErrorPlot (d, mu, sigma, color)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% %% Author: Marshall Herr %% %% Purpose: To make nice plots of the error vs range of VANTAGE %% %% Inputs: %% - r: A vector of the range of each datapoint %% - mu: The mean error at each range given in r %% - sigma: The standard deviation of the error at each range given in %% r %% %% Outputs: %% - A cool plot %% %% Date Created: 22 March 2019 %% %% Last Editted: 22 March 2019 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Definition at line 621 of file Validate.m.
References Model.Deployer, Deployer.testScenario, and Deployer.TruthFileName.
function GenerateOutputFiles (matFileDirectory)
% Generate output report %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% Modular data output files
Generate output report to transmit back to deployer system
Parameters
matFileDirectory Directory containing mat files
Returns
Author
Dylan Bossie
Date
21-Apr-2019
Definition at line 764 of file Validate.m.
function [ pos_err , time_interp ] = InterpolateDistance (CSArray, timefitted, time, distance)
Author
Dylan Bossie
Date
11-Apr-2019
Required fields of CSArray:
Required fields of timefitted:
Definition at line 302 of file Validate.m.
Referenced by Validate.ErrorAnalysis().
function masterPlotter (dataDirectory)
% Generates all of the plots {
This code shall produce four plots. 1) A contour plot which shows the error of the VANTAGE system as a function of distance and velocity 2) a plot of the velocity averaged errors as a function of distance for each type of test as well as a "weighted average" of the error using the errors of each of the three tests to construct one continuous "expected performance" across the entire distance domain; 3) a plot which shows the error in velocity as a function of velocity; 4) a plot which shows the deployment error as a function of velocity
Parameters
dataDirectory the path to the directory containing three folders: "Modular", "100m", and "Simulation". in each folder will reside all of the raw test .mat files which contain structs with the following fields: distance = the truth data distance vector; velocity = the average truth data velocity; t_err = the launch time error; v_err = the error in the measured average velocity as compared to the truth average velocity; pos_err = the magnitude of the error in position at every point contained in the distance field above
Author
Marshall Herr
Date
16-Apr-2019
Definition at line 1721 of file Validate.m.
References Validate.convolveMeasurements(), Validate.errorPlot(), and Validate.extractMatFileData().
function nicePlot (x, y, linespec, colors, plotLabels, plotTitle, legend_str, x_range)
% Makes nice plots
This code makes nice plots
Parameters
x A cell array of x axis plot vectors
y A cell array of y axis plot vectors
linespec a cell array of string containing plotting specifications
colors a cell array of color vectors
plotLabels a cell containing {xlabel,ylabel}
plotTitle a string containing the plot title
legend_str a cell array of strings which shall label each line
x_range a 2 length vector containing [xmin,xmax]
Returns
f The figure handle
Author
Marshall Herr
Date
21-Apr-2019
Definition at line 1884 of file Validate.m.
function [ updatedTruth , dt , n_vec , theta , offset_vec ] = PerformTruthDataCorrelation (MeasuredDataArray, TruthData, mostTrustedCubesat, should_debug)
% Correlate the truth data of a single, most trusted CubeSat {
Preforms timestamp corrections, data rotation, and data translation to the truth data input such that it matches the TOF data as closely as possible for the most trusted CubeSat
Parameters
MeasuredDataArray a crazy struct which has position and time measurements burried somewhere in it
TruthData this is a crazy struct with more in it than I comprehend
Returns
updatedTruth another crazy struct formatted identically to TruthData with the timestamp corrected, rotated, translated truth data within it
dt The time shifting scalar applied to the truth data timestamps
n_vec The vector about which the truth data is rotated
theta The angle [rad] of the rotation around n_vec
offset_vec The translation applied to the truth data
Author
Marshall Herr
Date
14-Apr-2019
Required fields of TruthData:
Generated fields of updatedTruth:
Definition at line 879 of file Validate.m.
References Validate.CorrelationMachine().
function [ updatedTruth , dt , n_vec , theta , offset_vec ] = PerformTruthDataCorrelationMultiple (MeasuredDataArray, TruthData)
% Correlate the truth data using a weighted sum of all CubeSats {
Preforms timestamp corrections, data rotation, and data translation to the truth data input such that it matches the TOF data as closely as possible for the weighted sum of all cubesat's corrections
Parameters
MeasuredDataArray a crazy struct which has position and time measurements burried somewhere in it
TruthData this is a crazy struct with more in it than I comprehend
Returns
updatedTruth another crazy struct formatted identically to TruthData with the timestamp corrected, rotated, translated truth data within it
dt The time shifting scalar applied to the truth data timestamps
n_vec The vector about which the truth data is rotated
theta The angle [rad] of the rotation around n_vec
offset_vec The translation applied to the truth data
Author
Marshall Herr
Date
15-Apr-2019
Required fields of TruthData:
Generated fields of updatedTruth:
Definition at line 1514 of file Validate.m.
References Validate.CorrelationMachine().
Referenced by Validate.Validate().
function [ Error , XError , YError , ZError ] = ProcessError (CubeSat, Truth)
% Plot error
Compute error between CubeSat and truth, plot results
Parameters
Definition at line 200 of file Validate.m.
function TOFpresentErrorsVsReqs (Model, SensorData) private
TOF Processing.
Present TOF Errors vs Reqs
Parameters
Definition at line 2291 of file Validate.m.
Referenced by Validate.validateTOF().
function validateTOF ()
% Validate TOF %% Housekeeping and Allocation
Parameters
Definition at line 92 of file Validate.m.
References Validate.TOFpresentErrorsVsReqs().
function WriteUpdatedTruthData (updatedTruth, TruthFileName, dt, n_vec, theta, offset_vec)
% Write out new corrected truth data json text file and json corrections file gets the absolute path to the file
Creates/overwrites files in the directory where the original truth file was from in which will lie the corrected truth data in one and the correction terms in the other
Parameters
updatedTruth crazy truth structure to be friday the 13thed
TruthFileName the truth data file relative path
dt the timestamp correction
n_vec the rotation correction vector
theta the rotation correction angle
offset_vec the translation correction vector
Author
Marshall Herr
Date
15-Apr-2019
Definition at line 1674 of file Validate.m.
Referenced by Validate.Validate().
Member Data Documentation
ComputingResults
Definition at line 34 of file Validate.m.
CorrelateTruthData
Boolean for whether or not to auto update truth data.
Definition at line 27 of file Validate.m.
ModelRef
Model handle class.
Definition at line 36 of file Validate.m.
Referenced by Validate.Validate().
The documentation for this class was generated from the following file:
+VANTAGE/+PostProcessing/Validate.m