VANTAGE Software: Optical Class Reference
Optical Class Reference
% Classdef This class will contain the functions necessary for the post-processing of optical camera data % Properties
Public Member Functions
Optical (ModelRef, configFilename, numCubesats)
% Class Constructor:
function [ didRead , direc , timing ] = readInputFramesFromImages (Model)
% Read data directory Read and process input from directory of images
function [ this , UnitOriginVCF , timestamp , isSystemCentroid ] = OpticalProcessing (image, BackgroundPixels, firstFrame)
% Perform optical processing Process optical frames to find the estimated cubesat positions
function frame = CleanupData (frame, background, firstFrame)
% Perform data cleanup Take data from test and clean regions with background noise not relevant to the test
function [ binarizedFrame , frame ] = FindBackground (firstFrame)
% Background Subtraction - Find background noise Take data from test and clean regions with background noise not relevant to the test
function [ this , isSystemCentroid ] = ImageProcessing (frame, BackgroundPixels, firstFrame)
% Perform image processing Execute frame processing based on provided automated naming convention
function plotObjectBoundaries (grayImage, boundaries, centroids, isSystemCentroid, binarizedImage)
% Plot boundaries Plot results from bwboundaries
function centroids = findCentroids (CubeSats)
% Find Object Centroids Use CubeSat boundaries to determine their respective centroid locations in the image
function this = objectAssociation (centroids)
% Object Association After bodies and their respective centroids have been identified, this function will associate them with relative identities based on their launch order 1-6 (1: first launched, 6: last launched)
function this = findLastImagePixel (imageFile, BackgroundPixels, firstFrame)
% Detect 100m Pixel Location Object association requires knowledge of the final pixel location of the system at 100m. This method will analyze the last image and detect this point
function linearExtrapolation (centroids, centerpoint, occlusion)
% Linear Extrapolation For the case of an object being occluded, a linear extrapolation will be performed based on its velocity calculated in the previous frames to approximate its next centroid location
function CubeSats = detectObjects (I_boundaries, I_binarized)
% Detect Objects Remove noisy boundaries found in the image, leaving only distinct boundaries corresponding to CubeSats
function cutPoly = occlusionCut (x, y, numCubesats)
% obfuscation identification for cubesat boundaries
function this = PixelToUnitVec (isSystemCentroid)
Convert pixel location to VCF unit vector Read optical camera parameters.
function PixelLocations = UnitVecToPixels (UnitVecs)
Convert pixel location to VCF unit vector Read optical camera parameters.
function I_binarized = Binarization (I_gray)
Convert pixel location to VCF unit vector.
function optWeight = OpticalWeighting (unused1)
Get desired weight for optical camera measurements based on current range.
Public Attributes
CurrentFrameCount
Current frame of data folder.
DesiredFPS
Desired FPS.
Frame
Current frame.
Image
Processed frame.
FrameIntervals
Timesteps corresponding to desired FPS.
CubeSats
CubeSat centroid data containers.
DataDirec
Daat directory.
PlotBinarizedImages
Plotting option (binarized images)
PlotCentroids
PlotHist
PlotAny
PlotCubeSats
PlotIBoundaries
Model ModelRef
Model handle class.
FileExtension
Data filenames.
PixelLocation100m
Pixel location of system centroid at 100m.
isInitialSearch
Check if performing search for 100m pixel.
RunOcclusion
Run occlusion centroid detection.
TestType
Type of test being evaluated.
CleanModular
Modular data region to clean.
Clean100m
100m data region to clean
PerformDataCleaning
Boolean for if data should be cleaned before processing.
Timestamps
Storage for relative timestamps for sensor fusion comparison.
rangeStart = 4
Range for starting optical processing.
Private Member Functions
function y = roundToNearestOdd (x)
function bSign = binarySign (num)
Private Attributes
width = 3088
Width of camera resolution.
height = 2076
Height of camera resolution.
Detailed Description
% Classdef This class will contain the functions necessary for the post-processing of optical camera data % Properties
Definition at line 19 of file Optical.m.
Constructor & Destructor Documentation
Optical (ModelRef, configFilename, numCubesats)
% Class Constructor:
Parameters
configFilename The configuration filename
numCubesats Number of expected cubesats
Returns
A reference to an initialized CubeSat object
Required fields of ModelRef:
Definition at line 203 of file Optical.m.
References Optical.FrameIntervals, Optical.ModelRef, and CubeSat_Optical.tag.
Member Function Documentation
function I_binarized = Binarization (I_gray)
Convert pixel location to VCF unit vector.
Parameters
I_gray Grayscale image of current frame
Returns
I_binarized Adaptively binarized image
Author
Dylan Bossie
Date
16-Mar-2019
Definition at line 1236 of file Optical.m.
References Optical.roundToNearestOdd().
Referenced by Optical.ImageProcessing().
function bSign = binarySign (num) private
Definition at line 1336 of file Optical.m.
Referenced by Optical.roundToNearestOdd().
function frame = CleanupData (frame, background, firstFrame)
% Perform data cleanup Take data from test and clean regions with background noise not relevant to the test
Dylan Bossie
Date
17-Mar-2019
Definition at line 354 of file Optical.m.
Referenced by Optical.ImageProcessing().
function CubeSats = detectObjects (I_boundaries, I_binarized)
% Detect Objects Remove noisy boundaries found in the image, leaving only distinct boundaries corresponding to CubeSats
Parameters
I_boundaries Contains a cell array of object boundaries found in the image
Author
Dylan Bossie
Date
26-Jan-2019
Definition at line 717 of file Optical.m.
Referenced by Optical.ImageProcessing().
function [ binarizedFrame , frame ] = FindBackground (firstFrame)
% Background Subtraction - Find background noise Take data from test and clean regions with background noise not relevant to the test
Parameters
frame Current binarized frame
Author
Dylan Bossie
Date
31-Mar-2019
Required fields of firstFrame:
Definition at line 387 of file Optical.m.
Referenced by Model.ComputeStateOutput().
function centroids = findCentroids (CubeSats)
% Find Object Centroids Use CubeSat boundaries to determine their respective centroid locations in the image
Parameters
CubeSats Boundaries of each CubeSat
Author
Dylan Bossie
Date
26-Jan-2019
Definition at line 581 of file Optical.m.
Referenced by Optical.ImageProcessing().
function this = findLastImagePixel (imageFile, BackgroundPixels, firstFrame)
% Detect 100m Pixel Location Object association requires knowledge of the final pixel location of the system at 100m. This method will analyze the last image and detect this point
Parameters
centroids Pixel location of centroid in image Grab image
centerpoint Pixel location of image center
occlusion Boolean array of tags descripting whether or not the respective centroid contains occluded bodies
Author
Dylan Bossie
Date
14-Feb-2019
Required fields of imageFile:
Generated fields of this:
Definition at line 641 of file Optical.m.
References Optical.ImageProcessing().
Referenced by Model.ComputeStateOutput().
function [ this , isSystemCentroid ] = ImageProcessing (frame, BackgroundPixels, firstFrame)
% Perform image processing Execute frame processing based on provided automated naming convention
Author
Dylan Bossie
Date
24-Jan-2019
Generated fields of this:
Definition at line 419 of file Optical.m.
References Optical.Binarization(), Optical.CleanupData(), Model.Deployer, Optical.detectObjects(), Optical.findCentroids(), Deployer.GetNumCubesats(), Optical.objectAssociation(), Optical.occlusionCut(), Optical.plotObjectBoundaries(), and Optical.TestType.
Referenced by Optical.findLastImagePixel(), and Optical.OpticalProcessing().
function linearExtrapolation (centroids, centerpoint, occlusion)
% Linear Extrapolation For the case of an object being occluded, a linear extrapolation will be performed based on its velocity calculated in the previous frames to approximate its next centroid location
Parameters
centroids Pixel location of centroid in image Get distance from centerpoint for all objects
centerpoint Pixel location of image center
occlusion Boolean array of tags descripting whether or not the respective centroid contains occluded bodies
Author
Dylan Bossie
Date
14-Feb-2019
Definition at line 678 of file Optical.m.
function this = objectAssociation (centroids)
% Object Association After bodies and their respective centroids have been identified, this function will associate them with relative identities based on their launch order 1-6 (1: first launched, 6: last launched)
Parameters
centroids Pixel location of centroid in image Get distance from final pixel location for all objects
centerpoint Pixel location of image center
occlusion Boolean array of tags descripting whether or not the respective centroid contains occluded bodies
Author
Dylan Bossie
Date
14-Feb-2019
Definition at line 604 of file Optical.m.
Referenced by Optical.ImageProcessing().
function cutPoly = occlusionCut (x, y, numCubesats)
% obfuscation identification for cubesat boundaries
This function takes boundary points found after binarization and separates it into multiple cubesats that are obfuscated
Parameters
x x coordinates of boundary
y y coordinates of boundary
posCase The position case d is diagonal, h is horizontal, v is vertical
numCubesats The number cubesats
Returns
cell array of identified polyshapes
Author
Justin Fay
Date
21-Feb-2019
Definition at line 851 of file Optical.m.
References Model.Deployer, Optical.Frame, Deployer.GetDeploymentTube(), and Deployer.GetVantageTube().
Referenced by Optical.ImageProcessing().
function [ this , UnitOriginVCF , timestamp , isSystemCentroid ] = OpticalProcessing (image, BackgroundPixels, firstFrame)
% Perform optical processing Process optical frames to find the estimated cubesat positions
Parameters
image Cell array with information on current image
BackgroundPixels Pixel locations of known background regions to be subtracted Grab image
Returns
this Updated Optical object containing detected CubeSat unit vectors and centroid pixel locations
UnitOriginVCF VCF origin location of VCF frame
timestamp Timestamp of current image
isSystemCentroid Boolean for if objects are occluded Dylan Bossie
Date
17-Mar-2019
Required fields of image:
Definition at line 307 of file Optical.m.
References Optical.ImageProcessing(), and Optical.PixelToUnitVec().
Referenced by Model.ComputeStateOutput().
function optWeight = OpticalWeighting (unused1)
Get desired weight for optical camera measurements based on current range.
Parameters
predRange Predicted mean range of CubeSats
Returns
optWeight Desired weight (0-1) of optical cam for sensor fusion
Author
Dylan Bossie
Date
7-Apr-2019
Parameters
unused1 Marked as "~" in original m-file.
Definition at line 1302 of file Optical.m.
Referenced by Model.SensorFusion().
function this = PixelToUnitVec (isSystemCentroid)
Convert pixel location to VCF unit vector Read optical camera parameters.
Parameters
isSystemCentroid Boolean for if converting a system centroid or a series of centroids
Returns
this Updated object
Author
Dylan Bossie
Date
4-Mar-2019
Definition at line 1136 of file Optical.m.
Referenced by Optical.OpticalProcessing().
function plotObjectBoundaries (grayImage, boundaries, centroids, isSystemCentroid, binarizedImage)
% Plot boundaries Plot results from bwboundaries
Parameters
CubeSats Contains a cell array of object boundaries found in the image
centerpoint Pixel location of image center
centroids Centroid locations of objects found in image
Author
Dylan Bossie
Date
26-Jan-2019
Definition at line 534 of file Optical.m.
Referenced by Optical.ImageProcessing().
function [ didRead , direc , timing ] = readInputFramesFromImages (Model)
% Read data directory Read and process input from directory of images
Parameters
this The object
Returns
didRead returns true if the file was read successfully, false otherwise
Author
Justin Fay
Date
10-Mar-2019
Required fields of Model:
Definition at line 258 of file Optical.m.
Referenced by Model.ComputeStateOutput().
function y = roundToNearestOdd (x) private
Definition at line 1331 of file Optical.m.
References Optical.binarySign().
Referenced by Optical.Binarization().
function PixelLocations = UnitVecToPixels (UnitVecs)
Convert pixel location to VCF unit vector Read optical camera parameters.
Parameters
UnitVecs List of unit vectors for each C.S. centroid
Returns
PixelLocations List of pixel locations for each C.S. centroid
Author
Dylan Bossie
Date
5-Mar-2019
Definition at line 1196 of file Optical.m.
Member Data Documentation
Clean100m
100m data region to clean
Definition at line 167 of file Optical.m.
CleanModular
Modular data region to clean.
Definition at line 160 of file Optical.m.
CubeSats
CubeSat centroid data containers.
Definition at line 86 of file Optical.m.
Referenced by Model.ComputeStateOutput().
CurrentFrameCount
Current frame of data folder.
Definition at line 51 of file Optical.m.
Referenced by Model.ComputeStateOutput().
DataDirec
Daat directory.
Definition at line 93 of file Optical.m.
Referenced by Model.ComputeStateOutput().
DesiredFPS
Desired FPS.
Definition at line 58 of file Optical.m.
FileExtension
Data filenames.
Definition at line 125 of file Optical.m.
Frame
Current frame.
Definition at line 65 of file Optical.m.
Referenced by Model.ComputeStateOutput(), and Optical.occlusionCut().
FrameIntervals
Timesteps corresponding to desired FPS.
Definition at line 79 of file Optical.m.
Referenced by Optical.Optical().
height = 2076 private
Height of camera resolution.
Default: 2076
Definition at line 39 of file Optical.m.
Image
Processed frame.
Definition at line 72 of file Optical.m.
isInitialSearch
Check if performing search for 100m pixel.
Definition at line 139 of file Optical.m.
ModelRef
Model handle class.
Definition at line 117 of file Optical.m.
Referenced by Optical.Optical().
PerformDataCleaning
Boolean for if data should be cleaned before processing.
Definition at line 174 of file Optical.m.
PixelLocation100m
Pixel location of system centroid at 100m.
Definition at line 132 of file Optical.m.
PlotAny
Definition at line 111 of file Optical.m.
PlotBinarizedImages
Plotting option (binarized images)
Definition at line 100 of file Optical.m.
PlotCentroids
Definition at line 107 of file Optical.m.
PlotCubeSats
Definition at line 113 of file Optical.m.
PlotHist
Definition at line 109 of file Optical.m.
PlotIBoundaries
Definition at line 115 of file Optical.m.
rangeStart = 4
Range for starting optical processing.
Default: 4
Definition at line 188 of file Optical.m.
Referenced by Model.ComputeStateOutput(), and TOF.TofWeighting().
RunOcclusion
Run occlusion centroid detection.
Definition at line 146 of file Optical.m.
TestType
Type of test being evaluated.
Definition at line 153 of file Optical.m.
Referenced by Optical.ImageProcessing().
Timestamps
Storage for relative timestamps for sensor fusion comparison.
Definition at line 181 of file Optical.m.
Referenced by Model.ComputeStateOutput().
width = 3088 private
Width of camera resolution.
Default: 3088
Definition at line 30 of file Optical.m.
The documentation for this class was generated from the following file:
+VANTAGE/+PostProcessing/Optical.m