VANTAGE Software: Transform Class Reference
Transform Class Reference
% Classdef A class used to save transform information from the cartesian 3-dimensional frame srcFrame to the cartesian 3-dimensional frame targFrame. It is then used to transform a set of data in srcFrame to a set of data in targFrame.
Public Member Functions
Transform (configFilename)
% Class Constructor
function output = tf (targFrame, data, srcFrame)
% Execute transform Execute transformations between frames Error catching
Public Attributes
TDATA
nomen
cell mapping frame names to indices in TDATA
maxNomen = 10
maximum allowable number of nomen entries (number of defined frames)
Private Member Functions
function this = setTdata (targFrame, C, V, srcFrame)
% Save transform matrices and translation vectors to TDATA Error catching
function row = findNomen (str)
% Index into nomen
Detailed Description
% Classdef A class used to save transform information from the cartesian 3-dimensional frame srcFrame to the cartesian 3-dimensional frame targFrame. It is then used to transform a set of data in srcFrame to a set of data in targFrame.
% Properties
Definition at line 19 of file Transform.m.
Constructor & Destructor Documentation
Transform (configFilename)
% Class Constructor
Constructs class using Transform.json config file
Parameters
configFilename relative path to JSON config file
Returns
Class instance
Author
Joshua Kirby
Date
17-Feb-2019
Definition at line 55 of file Transform.m.
References Transform.setTdata().
Member Function Documentation
function row = findNomen (str) private
% Index into nomen
Return row number of string location in this.nomen
Parameters
str string to be found in this.nomen
Returns
index of string in this.nomen, set to 0 if string not found
Author
Joshua Kirby
Date
24-Jan-2019
Definition at line 232 of file Transform.m.
Referenced by Transform.setTdata(), and Transform.tf().
function this = setTdata (targFrame, C, V, srcFrame) private
% Save transform matrices and translation vectors to TDATA Error catching
Records transform matrices and translation vectors between specific frames in TDATA
Parameters
targFrame identifier for the target frame, char
C 3x3 transformation matrix from source frame to target frame
V 3x1 translation vector from the origin of srcFrame to the origin of targFrame (expressed in srcFrame), cell
srcFrame identifier for the source frame, char
Author
Joshua Kirby
Date
24-Jan-2019
Definition at line 153 of file Transform.m.
References Transform.findNomen(), and Transform.TDATA.
Referenced by Transform.Transform().
function output = tf (targFrame, data, srcFrame)
% Execute transform Execute transformations between frames Error catching
Parameters
targFrame identifier for the target frame, char
data a 3xn set of vectors in the srcFrame to be transformed to the targFrame, matrix
srcFrame identifier for the source frame, char
Returns
a 3xn set of vectors in the targFrame, matrix
Author
Joshua Kirby
Date
24-Jan-2019
Definition at line 85 of file Transform.m.
References Transform.findNomen(), and Transform.TDATA.
Referenced by TOF.associateCentroids(), and TOF.plotResults().
Member Data Documentation
maxNomen = 10
maximum allowable number of nomen entries (number of defined frames)
Default: 10
Definition at line 42 of file Transform.m.
nomen
cell mapping frame names to indices in TDATA
Definition at line 35 of file Transform.m.
TDATA
Definition at line 33 of file Transform.m.
Referenced by Transform.setTdata(), and Transform.tf().
The documentation for this class was generated from the following file:
+VANTAGE/+PostProcessing/Transform.m