VANTAGE Software: TOF Class Reference
TOF Class Reference
% Classdef A class representing the Time of Flight Camera used by VANTAGE
Public Member Functions
TOF (ModelRef, configFilename)
Constructor Clear persistents.
function maxAllowableRange = getMaxAllowableRange ()
% Getters
function sigmaTOF = TofWeighting (predMeanRange)
Returns the TOF weight given a predicted mean range of cubesats.
function Deployer = TOFProcessing (SensorData, Deployer, varargin)
% TOF Processing Extract relevant data from inputs
function [ CubeSats_TOF , pc ] = naiveFindCentroids (filename, time, SensorData, CubeSats_TOF)
% Calculate centroids from file Extract point cloud locations
function [ CubeSats , numConsOutliers ] = associateCentroids (CubeSats_TOF, CubeSats, numConsOutliers, SensorData)
% Associate centroids from CubeSats_TOF with CubeSats
Public Attributes
maxAllowableRange
Maximum range within which TOF data is considered valid, m.
ptMaxDistFromPlane
Maximum allowed distance from a plane to be considered part of the plane.
faceLenMatchTol = 0.02
Face length matching tolerance, for use in centroid1 method m.
Model ModelRef
Reference to Model class.
fps
fps
HVfov_deg
fov
showDebugPlots = 0
showDebugPlots, default to 0
maxConsOutliers = 3
max number of consecutive outliers for a CubeSat
outlierMultiplier = 10
scalar by which to multiply the standard deviation of all previous centroid measurements for each CubeSat, the value (outlierMultiplier*stdOfAllPreviousMeas) is used as the threshold for separating outliers from valid data points
Protected Member Functions
function pc = loadPcFile (filename)
% Loading point clouds from files
function [ this , CubeSats_TOF ] = cubesatPointsFromPC (pc, CubeSats_TOF)
% Identifying cubesats within point clouds Pull out z values
function CubeSat_TOF = fitPlanesToCubesat (CubeSat_TOF)
% Identifying visible planes for a cubesat %% Allocation Initial value for minimum number of points considered to make up a plane
function CubeSat = findCentroidFromFaces (CubeSat)
% Calculating centroids from identified planes for a cubesat Find centroid based on number of identified faces
function CubeSat_TOF = centroid1 (CubeSat_TOF)
%% Find plane boundary points and centroid
function CubeSat_TOF = centroid2 (CubeSat_TOF)
%% Check that planes intersect as expected
function CubeSat_TOF = centroid3 (CubeSat_TOF)
%% Find faces' centroids and corners %% and determine if each face qualifies as a fullFace
function faces = getFaceCentroidAndCorners (faces)
% Subroutines
function CubeSat_TOF = diagnoseFace (CubeSat_TOF)
%% for all faces
function [ n , V , p ] = affine_fit (X)
the mean of the samples belongs to the plane
function d = distInFromFace (CubeSat, faceIndex)
Dimensions to choose from, corresponding to indices of CubeSat.actualDims.
function uvec = unitvec (vec)
function plotResults (CubeSats, CubeSats_TOF, pc, time, numConsOutliers)
function bb = minBoundingBox (X)
function y = roundToNearestOdd (x)
function bSign = binarySign (num)
function [ pX , pY , pZ , stdXYZ ] = fitLineToCentroids (CubeSat, N)
Evaluate N.
function TOFfit_VCF = produceFinalTOFfit (CubeSat)
Detailed Description
% Classdef A class representing the Time of Flight Camera used by VANTAGE
% Properties
Definition at line 19 of file TOF.m.
Constructor & Destructor Documentation
TOF (ModelRef, configFilename)
Constructor Clear persistents.
Parameters
modelRef Model class handle (
See also
Model)
Parameters
configFileneame The configuration filename
Returns
A reference to an initialized TOF object
Definition at line 109 of file TOF.m.
References TOF.associateCentroids(), and TOF.ModelRef.
Member Function Documentation
function [ n , V , p ] = affine_fit (X) protected
the mean of the samples belongs to the plane
Computes the plane that fits best (least square of the normal distance to the plane) a set of sample points.
Parameters
X a N by 3 matrix where each line is a sample point
Returns
a unit(column) vector normal to the plane
a 3 by 2 matrix, the columns of V form an orthonormal basis of the plane
a point belonging to the plane
Author
Adrien Leygue
Date
30-Aug-2013
Note
This method has non-standard access specifiers: Access = (VANTAGE.Test.PostProcessing.Test_TOF)
Definition at line 1334 of file TOF.m.
Referenced by TOF.fitPlanesToCubesat().
function [ CubeSats , numConsOutliers ] = associateCentroids (CubeSats_TOF, CubeSats, numConsOutliers, SensorData)
% Associate centroids from CubeSats_TOF with CubeSats
Parameters
CubeSats_TOF CubeSat_TOF object with naive centroids in TCF
CubeSats CubeSat object with all previous centroids in VCF
numConsOutliers a 1xlength(CubeSats) vector of the number of consecutive outliers for each CubeSat identified thus far
Returns
CubeSats object with a new set of centroids from CubeSats_TOF
updated numConsOutliers vector
Author
Joshua Kirby
Date
10-Mar-2019
Required fields of CubeSats_TOF:
Required fields of CubeSats:
Definition at line 383 of file TOF.m.
References Model.Deployer, TOF.fitLineToCentroids(), Deployer.numCubesats, Deployer.testScenario, Transform.tf(), and Model.Transform.
Referenced by TOF.TOF(), and TOF.TOFProcessing().
function bSign = binarySign (num) protected
Definition at line 1625 of file TOF.m.
Referenced by TOF.roundToNearestOdd().
function CubeSat_TOF = centroid1 (CubeSat_TOF) protected
%% Find plane boundary points and centroid
Calculates the CubeSat centroid from a single identified face by projecting inward from the face to the centroid. Assumes that the expectedU of the CubeSat is the actual U
Parameters
CubeSat CubeSat object to be analyzed
See also
CubeSat
Returns
CubeSat CubeSat object with calculated TCF centroid populated
Author
Joshua Kirby
Date
03-Feb-2019
Required fields of CubeSat_TOF:
Generated fields of CubeSat_TOF:
Note
This method has non-standard access specifiers: Access = (VANTAGE.Test.PostProcessing.Test_TOF)
Definition at line 937 of file TOF.m.
References TOF.diagnoseFace(), TOF.distInFromFace(), TOF.getFaceCentroidAndCorners(), and TOF.unitvec().
Referenced by TOF.findCentroidFromFaces().
function CubeSat_TOF = centroid2 (CubeSat_TOF) protected
%% Check that planes intersect as expected
Calculates the CubeSat centroid from two identified faces by projecting inward from the faces to the centroid. Assumes that the expectedU of the CubeSat is the actual U
Parameters
CubeSat CubeSat object to be analyzed
See also
CubeSat
Returns
CubeSat CubeSat object with calculated TCF centroid populated
Author
Joshua Kirby
Date
03-Feb-2019
Required fields of CubeSat_TOF:
Generated fields of CubeSat_TOF:
Note
This method has non-standard access specifiers: Access = (VANTAGE.Test.PostProcessing.Test_TOF)
Definition at line 1009 of file TOF.m.
References TOF.diagnoseFace(), TOF.distInFromFace(), and TOF.getFaceCentroidAndCorners().
Referenced by TOF.findCentroidFromFaces().
function CubeSat_TOF = centroid3 (CubeSat_TOF) protected
%% Find faces' centroids and corners %% and determine if each face qualifies as a fullFace
Calculates the CubeSat centroid from three identified faces by projecting inward from the faces to the centroid. Assumes that the expectedU of the CubeSat is the actual U
Parameters
CubeSat_TOF CubeSat object to be analyzed
See also
CubeSat
Returns
CubeSat object with calculated TCF centroid populated
Author
Joshua Kirby
Date
03-Feb-2019
Generated fields of CubeSat_TOF:
Note
This method has non-standard access specifiers: Access = (VANTAGE.Test.PostProcessing.Test_TOF)
Definition at line 1086 of file TOF.m.
References TOF.diagnoseFace(), TOF.distInFromFace(), and TOF.getFaceCentroidAndCorners().
Referenced by TOF.findCentroidFromFaces().
function [ this , CubeSats_TOF ] = cubesatPointsFromPC (pc, CubeSats_TOF) protected
% Identifying cubesats within point clouds Pull out z values
Separates a raw point cloud into the points associated with distinct cubesats
Parameters
pc raw point cloud from file
CubeSats_TOF initialized array of CubeSat_TOF objects ordered [first-out to last-out] and containing expectedU and actualDims
Returns
array of identified cubesats
See also
CubeSat_TOF class
Author
Joshua Kirby
Date
03-Feb-2019
Required fields of pc:
Note
This method has non-standard access specifiers: Access = (VANTAGE.Test.PostProcessing.Test_TOF)
Definition at line 681 of file TOF.m.
References TOF.HVfov_deg.
Referenced by TOF.naiveFindCentroids().
function CubeSat_TOF = diagnoseFace (CubeSat_TOF) protected
%% for all faces
Determines if a CubeSat.face struct is a full CubeSat face
CubeSat_TOF CubeSat_TOF object with faces struct already updated using getFaceCentroidAndCorners
Returns
CubeSat_TOF with fullFace boolean, trusted side lengths, trusted corners, and face index
Author
Joshua Kirby
Date
07-Mar-2019
Required fields of CubeSat_TOF:
Note
This method has non-standard access specifiers: Access = (VANTAGE.Test.PostProcessing.Test_TOF)
Definition at line 1204 of file TOF.m.
References TOF.unitvec().
Referenced by TOF.centroid1(), TOF.centroid2(), and TOF.centroid3().
function d = distInFromFace (CubeSat, faceIndex) protected
Dimensions to choose from, corresponding to indices of CubeSat.actualDims.
Calculate distance to project perpendicularly inward from a face to the cubesat centerline
Parameters
CubeSat instance of VANTAGE.PostProcessing.CubeSat_TOF
See also
CubeSat_TOF
Parameters
faceArea index of face, indices correspond to faces composed of CubeSat.actualDims([combnk(1:3,2)](index,i))
Returns
perpendicular distance from face to centroid
Author
Joshua Kirby
Date
07-Feb-2019
Required fields of CubeSat:
Note
This method has non-standard access specifiers: Access = (VANTAGE.Test.PostProcessing.Test_TOF)
Definition at line 1368 of file TOF.m.
Referenced by TOF.centroid1(), TOF.centroid2(), and TOF.centroid3().
function CubeSat = findCentroidFromFaces (CubeSat) protected
% Calculating centroids from identified planes for a cubesat Find centroid based on number of identified faces
Calculates centroids in TCF for a cubesat based on identified faces
Parameters
CubeSat CubeSat object to be analyzed
See also
CubeSat
Returns
CubeSat CubeSat object with calculated centroid populated
Author
Joshua Kirby
Date
03-Feb-2019
Required fields of CubeSat:
Note
This method has non-standard access specifiers: Access = (VANTAGE.Test.PostProcessing.Test_TOF)
Definition at line 904 of file TOF.m.
References TOF.centroid1(), TOF.centroid2(), and TOF.centroid3().
Referenced by TOF.naiveFindCentroids().
function [ pX , pY , pZ , stdXYZ ] = fitLineToCentroids (CubeSat, N) protected
Evaluate N.
Calculate polynomial fit coefficients and outlierThresholds along each axis for a given CubeSat object for the first N measurements in the CubeSat
Parameters
CubeSat CubeSat class instance containing centroids_VCF
N number of measurements to use (centroids_VCF(:,1:N), inf is allowed
Returns
polynomial fit coefficients along x, size 1x2
polynomial fit coefficients along y, size 1x2
polynomial fit coefficients along z, size 1x2
standard deviations along [x,y,z]'
Author
Joshua Kirby
Date
21-Mar-2019
Required fields of CubeSat:
Note
This method has non-standard access specifiers: Access = (VANTAGE.Test.PostProcessing.Test_TOF)
Definition at line 1633 of file TOF.m.
Referenced by TOF.associateCentroids().
function CubeSat_TOF = fitPlanesToCubesat (CubeSat_TOF) protected
% Identifying visible planes for a cubesat %% Allocation Initial value for minimum number of points considered to make up a plane
Identifies visible faces in a cubesat point cloud
Parameters
CubeSat CubeSat object to be analyzed
See also
CubeSat
Returns
CubeSat CubeSat object with identified planes populated
Author
Joshua Kirby
Date
03-Feb-2019
Required fields of CubeSat_TOF:
Generated fields of CubeSat_TOF:
Note
This method has non-standard access specifiers: Access = (VANTAGE.Test.PostProcessing.Test_TOF)
Definition at line 787 of file TOF.m.
References TOF.affine_fit().
Referenced by TOF.naiveFindCentroids().
function faces = getFaceCentroidAndCorners (faces) protected
% Subroutines
Smooths a face boundary and returns the smoothed boundary and face centroid
Parameters
faces CubeSat_TOF.faces struct
Returns
struct with identified face centroids and corners
Author
Joshua Kirby
Date
07-Mar-2019
Note
This method has non-standard access specifiers: Access = (VANTAGE.Test.PostProcessing.Test_TOF)
Definition at line 1147 of file TOF.m.
References TOF.minBoundingBox(), and TOF.roundToNearestOdd().
Referenced by TOF.centroid1(), TOF.centroid2(), and TOF.centroid3().
function maxAllowableRange = getMaxAllowableRange ()
% Getters
Returns the maxAllowableRange
Definition at line 146 of file TOF.m.
References TOF.maxAllowableRange.
function pc = loadPcFile (filename) protected
% Loading point clouds from files
Loads data from a simulation file
Parameters
filename filename, string
Returns
point cloud obtained from file
Author
Joshua Kirby
Date
24-Jan-2019
Note
This method has non-standard access specifiers: Access = (VANTAGE.Test.PostProcessing.Test_TOF)
Definition at line 634 of file TOF.m.
References Model.Deployer, and Deployer.testScenario.
Referenced by TOF.naiveFindCentroids().
function bb = minBoundingBox (X) protected
Author
Julien Diener
Date
05-Mar-2019 compute the minimum bounding box of a set of 2D points Use: boundingBox = minBoundingBox(point_matrix)
Input: 2xn matrix containing the [x,y] coordinates of n points *** there must be at least 3 points which are not collinear output: 2x4 matrix containing the coordinates of the bounding box corners
Example : generate a random set of point in a randomly rotated rectangle n = 50000; t = pi*rand(1); X = [cos(t) -sin(t) ; sin(t) cos(t)]*[7 0; 0 2]*rand(2,n); X = [X 20*(rand(2,1)-0.5)]; % add an outlier
tic c = minBoundingBox(X); toc
figure(42); hold off, plot(X(1,:),X(2,:),.) hold on, plot(c(1,[1:end 1]),c(2,[1:end 1]),r) axis equal
Note
This method has non-standard access specifiers: Access = (VANTAGE.Test.PostProcessing.Test_TOF)
Definition at line 1539 of file TOF.m.
Referenced by TOF.getFaceCentroidAndCorners().
function [ CubeSats_TOF , pc ] = naiveFindCentroids (filename, time, SensorData, CubeSats_TOF)
% Calculate centroids from file Extract point cloud locations
Produces centroids of all CubeSats naively identified in a single point cloud
Parameters
filename filename for a single point cloud, char
time timestamp of this file, scalar
SensorData struct of information about sensors
CubeSats_TOF initialized array of CubeSat_TOF objects ordered [first-out to last-out] and containing expectedU and actualDims
Returns
length-n array of Cubesat_TOF's containing identified TCF centroids
raw point cloud from file
Author
Joshua Kirby
Date
04-Mar-2019
Required fields of SensorData:
Definition at line 326 of file TOF.m.
References TOF.cubesatPointsFromPC(), TOF.findCentroidFromFaces(), TOF.fitPlanesToCubesat(), and TOF.loadPcFile().
Referenced by TOF.TOFProcessing().
function plotResults (CubeSats, CubeSats_TOF, pc, time, numConsOutliers) protected
Definition at line 1410 of file TOF.m.
References Transform.tf(), Model.Transform, and Model.Truth_VCF.
Referenced by TOF.TOFProcessing().
function TOFfit_VCF = produceFinalTOFfit (CubeSat) protected
Definition at line 1691 of file TOF.m.
Referenced by TOF.TOFProcessing().
function y = roundToNearestOdd (x) protected
Definition at line 1620 of file TOF.m.
References TOF.binarySign().
Referenced by TOF.getFaceCentroidAndCorners().
function Deployer = TOFProcessing (SensorData, Deployer, varargin)
% TOF Processing Extract relevant data from inputs
Performs all TOF processing for VANTAGE
Parameters
SensorData struct of information about sensors
Deployer Deployer class instance, containing Cubesats and manifest data
Returns
Deployer class instance, containing Cubesats populated with TOF centroid results
Author
Joshua Kirby
Date
01-Mar-2019
Required fields of Deployer:
Required fields of SensorData:
Generated fields of Deployer:
Definition at line 183 of file TOF.m.
References TOF.associateCentroids(), Model.Deployer, TOF.naiveFindCentroids(), TOF.plotResults(), TOF.produceFinalTOFfit(), Deployer.testScenario, Model.TimeMan, and Model.Truth_VCF.
function sigmaTOF = TofWeighting (predMeanRange)
Returns the TOF weight given a predicted mean range of cubesats.
Parameters
predMeanRange predicted mean range of CubeSats, m
Returns
current TOF weight for sensor fusion
Author
Joshua Kirby
Date
07-Apr-2019
Definition at line 158 of file TOF.m.
References Model.Optical, and Optical.rangeStart.
Referenced by Model.SensorFusion().
function uvec = unitvec (vec) protected
Definition at line 1404 of file TOF.m.
Referenced by TOF.centroid1(), and TOF.diagnoseFace().
Member Data Documentation
faceLenMatchTol = 0.02
Face length matching tolerance, for use in centroid1 method m.
Default: 0.02
Definition at line 45 of file TOF.m.
fps
fps
Definition at line 62 of file TOF.m.
HVfov_deg
fov
Definition at line 69 of file TOF.m.
Referenced by TOF.cubesatPointsFromPC().
maxAllowableRange
Maximum range within which TOF data is considered valid, m.
Definition at line 31 of file TOF.m.
Referenced by TOF.getMaxAllowableRange().
maxConsOutliers = 3
max number of consecutive outliers for a CubeSat
Default: 3
Definition at line 84 of file TOF.m.
ModelRef
Reference to Model class.
Definition at line 54 of file TOF.m.
Referenced by TOF.TOF().
outlierMultiplier = 10
scalar by which to multiply the standard deviation of all previous centroid measurements for each CubeSat, the value (outlierMultiplier*stdOfAllPreviousMeas) is used as the threshold for separating outliers from valid data points
Default: 10
Definition at line 93 of file TOF.m.
ptMaxDistFromPlane
Maximum allowed distance from a plane to be considered part of the plane.
Definition at line 38 of file TOF.m.
showDebugPlots = 0
showDebugPlots, default to 0
Default: 0
Definition at line 76 of file TOF.m.
The documentation for this class was generated from the following file:
+VANTAGE/+PostProcessing/TOF.m