% Auto-generated by cameraCalibrator app on 27-Feb-2019
%-------------------------------------------------------


% Define images to process
imageFileNames = {'/home/vantage/Documents/githere/VANTAGE/Automation/TOF_Automation/examples/CheckerboardsI/funfunfun20.png',...
    '/home/vantage/Documents/githere/VANTAGE/Automation/TOF_Automation/examples/CheckerboardsI/funfunfun21.png',...
    '/home/vantage/Documents/githere/VANTAGE/Automation/TOF_Automation/examples/CheckerboardsI/funfunfun22.png',...
    '/home/vantage/Documents/githere/VANTAGE/Automation/TOF_Automation/examples/CheckerboardsI/funfunfun23.png',...
    '/home/vantage/Documents/githere/VANTAGE/Automation/TOF_Automation/examples/CheckerboardsI/funfunfun24.png',...
    '/home/vantage/Documents/githere/VANTAGE/Automation/TOF_Automation/examples/CheckerboardsI/funfunfun25.png',...
    '/home/vantage/Documents/githere/VANTAGE/Automation/TOF_Automation/examples/CheckerboardsI/funfunfun26.png',...
    '/home/vantage/Documents/githere/VANTAGE/Automation/TOF_Automation/examples/CheckerboardsI/funfunfun27.png',...
    '/home/vantage/Documents/githere/VANTAGE/Automation/TOF_Automation/examples/CheckerboardsI/funfunfun28.png',...
    };
% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Read the first image to obtain image size
originalImage = imread(imageFileNames{1});
[mrows, ncols, ~] = size(originalImage);

% Generate world coordinates of the corners of the squares
squareSize = 23;  % in units of 'millimeters'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% View reprojection errors
h1=figure; showReprojectionErrors(cameraParams);

% Visualize pattern locations
h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, cameraParams);

% For example, you can use the calibration data to remove effects of lens distortion.
undistortedImage = undistortImage(originalImage, cameraParams);

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('MeasuringPlanarObjectsExample')
% showdemo('StructureFromMotionExample')
