//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Multi_Cam.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_DLGSELECTCAMERA             103
#define IDR_MAINFRAME                   128
#define IDR_MULTI_CAMTYPE               129
#define IDC_LIST_CAMERAS                130
#define IDR_MAINFRAME_8BIT_DEPTH_DUMMY  131
#define IDB_BITMAP1                     139
#define IDD_DIALOG_TIMING               143
#define IDD_DIALOG_IMAGE                144
#define IDD_DIALOG_SIZE                 145
#define IDB_BITMAP2                     152
#define IDB_BITMAP3                     153
#define IDB_BITMAP4                     161
#define IDD_DIALOG_TRIGGER              162
#define IDC_SLIDER_PIXELCLOCK           1002
#define IDC_SLIDER_FRAMEDELAY           1003
#define IDC_SLIDER_EXPOSURE             1004
#define IDC_EDIT_RED                    1010
#define IDC_EDIT_GREEN                  1011
#define IDC_EDIT_BLUE                   1012
#define IDC_SPIN1                       1013
#define IDC_Gain                        1013
#define IDC_SPIN_WIDTH                  1013
#define IDC_SPIN_TRIGGER_DELAY          1013
#define IDC_SPIN2                       1015
#define IDC_FrameRate                   1015
#define IDC_SPIN_HEIGHT                 1015
#define IDC_SPIN_TRIGGER_TIMEOUT        1015
#define IDC_SPIN3                       1016
#define IDC_Time                        1016
#define IDC_SPIN_LEFT                   1016
#define IDC_PIXEL_CLOCK_MIN             1017
#define IDC_PIXEL_CLOCK_MAX             1018
#define IDC_STATIC_FRAMERATE_MIN        1019
#define IDC_STATIC_FRAMERATE_MAX        1020
#define IDC_STATIC_EXPOSURE_MIN         1021
#define IDC_STATIC_EXPOSURE_MAX         1022
#define IDC_PIXEL_CLOCK                 1023
#define IDC_STATIC_FRAMERATE            1024
#define IDC_STATIC_EXPOSURE             1025
#define IDC_BUTTON_DEFAULT              1026
#define IDC_BUTTON_DEFAULT2             1027
#define IDC_SLIDER_GAIN_MASTER          1028
#define IDC_EDIT_MASTER                 1029
#define IDC_GAINBOOST                   1030
#define IDC_SLIDER_BL_OFFSET            1031
#define IDC_EDIT_BL_OFFSET              1032
#define IDC_SLIDER_GAIN_RED             1033
#define IDC_SLIDER_GAIN_GREEN           1034
#define IDC_SLIDER_GAIN_BLUE            1035
#define IDC_SPIN4                       1036
#define IDC_GreenGain                   1036
#define IDC_SPIN_TOP                    1036
#define IDC_SPIN5                       1037
#define IDC_PixelClock                  1037
#define IDC_CHECK2                      1038
#define IDC_CHECK_GAMMA                 1038
#define IDC_SLIDER_GAMMA                1039
#define IDC_EDIT_GAMMA                  1040
#define IDC_SPIN6                       1041
#define IDC_Gamma                       1041
#define IDC_EDIT_PIXELCLOCK             1042
#define IDC_EDIT_FRAMERATE              1043
#define IDC_EDIT_EXPOSURE               1044
#define IDC_STATIC_GAIN_MIN             1045
#define IDC_STATIC_GAIN_MAX             1046
#define IDC_STATIC_BL_MIN               1047
#define IDC_STATIC_BL_MAX               1048
#define IDC_STATIC_RED_MIN              1049
#define IDC_STATIC_RED_MAX              1050
#define IDC_STATIC_GREEN_MIN            1051
#define IDC_STATIC_GREEN_MAX            1052
#define IDC_STATIC_BLUE_MIN             1053
#define IDC_STATIC_BLUE_MAX             1054
#define IDC_BlackLevel                  1055
#define IDC_RedGain                     1056
#define IDC_BlueGain                    1057
#define IDC_SLIDER_BREITE               1059
#define IDC_SLIDER_WIDTH                1059
#define IDC_SLIDER_HOEHE                1060
#define IDC_SLIDER_HIGH                 1060
#define IDC_SLIDER_LINKS                1061
#define IDC_SLIDER_LEFT                 1061
#define IDC_SLIDER_OBEN                 1062
#define IDC_SLIDER_TOP                  1062
#define IDC_EDIT_WIDTH                  1063
#define IDC_EDIT_HEIGHT                 1064
#define IDC_EDIT_LEFT                   1065
#define IDC_EDIT_TOP                    1066
#define IDC_STATIC_BREITE_MIN           1067
#define IDC_STATIC_BREITE_MAX           1068
#define IDC_STATIC_HOEHE_MIN            1069
#define IDC_STATIC_HOEHE_MAX            1070
#define IDC_STATIC_LEFT_MIN             1071
#define IDC_STATIC_LEFT_MAX             1072
#define IDC_STATIC_TOP_MIN              1073
#define IDC_STATIC_TOP_MAX              1074
#define IDC_CHECK_Normal                1075
#define IDC_CHECK_WINDOW                1076
#define IDC_RADIO_SOFTWARE              1078
#define IDC_RADIO_FALLING               1079
#define IDC_RADIO_RISING                1080
#define IDC_STATIC_DELAY                1081
#define IDC_SLIDER_TRIGGER_DELAY        1082
#define IDC_EDIT_TRIGGER_DELAY          1083
#define IDC_SLIDER_TRIGGER_TIMEOUT      1084
#define IDC_EDIT_TRIGGER_TIMEOUT        1085
#define IDC_STATIC_MIN_DELAY            1086
#define IDC_STATIC_MAX_DELAY            1087
#define IDC_STATIC_MIN_TIMEOUT          1088
#define IDC_STATIC_MAX_TIMEOUT          1089
#define IDC_CHECK1                      1090
#define IDC_CHECK_TRIGGER_DELAY         1090
#define ID_BUTTON_TRIGGER_FREEZE        32780
#define ID_FILE_SETTINGS                32781
#define ID_BUTTON_TRIGGER_CAPTURE       32782
#define ID_BUTTON_SAVE                  32783
#define ID_BUTTON_PARAMETER             32784
#define ID_VIEW_TIMESTAMP               32784
#define ID_BUTTON_SINGLE_TRIGGER        32785

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        163
#define _APS_NEXT_COMMAND_VALUE         32785
#define _APS_NEXT_CONTROL_VALUE         1091
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
